baseurl = "https://yamadayuki.github.io/es6-chat-alt-docs/"
languageCode = "en-us"
title = "My New Hugo"
theme = "hugo-material-docs"
canonifyurls = true

[params]
  author = "Yamada"
  description = "ES6 Chat"

  [params.palette]
    primary = "teal"
    accent  = "blue"

[[menu.main]]
  name   = "Getting start"
  url    = "/"
  weight = 0
